name: Dependent jobs
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "job1"

  job2:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: step-1
        run: echo "job2"
  
  job3:
    runs-on: ubuntu-latest
    needs: [ job1, job2 ]
    if: always() && (needs.job2.result == 'success' || needs.job2.result == 'skipped')
    steps:
      - name: step-1
        run: echo "job3"

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: step-1
        run: echo "job4"