name: check-ip-address

on:
  workflow_dispatch:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-ip
        run: ip add

  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: print-ip
        run: ip add
