name: check-ip-address

on:
  workflow_dispatch:
  push:

jobs:
  first-job:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: print-ip
        run: ip add
      - name: payload
        run: echo ${github.event}

  second-job:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: print-ip
        run: ip add
