name: Automate_Deploy_Test

on:
  push:
  workflow_dispatch:

jobs:
  first-job:
    env:
      name: raj
      age: 20
    runs-on: ubuntu-latest
    steps:
      - name: checkoutRepo
        uses: actions/checkout@v3
      - name: add variable to env
        run: |
          echo "tests=16" >> $GITHUB_ENV
          echo ${{env.name}}
          echo "name=rajkumar" >> $GITHUB_ENV
          echo ${{env.name}} ${{env.tests}}
      - name: access variable from env
        run: |
          echo $name
          echo $age
          echo $tests

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - name: access variable from env
        run: echo ${{env.tests}}
