name: Automate_Deploy_Test

on:
  workflow_dispatch:

jobs:
  weekend_deployment_check:
    runs-on: ubuntu-latest
    outputs:
      day: ${{ steps.check_day.outputs.day }}
    steps:
      - name: Check Day of the Week
        id: check_day
        run: |
          echo $(date +%u)
          echo "day=$(date +%u)" >> $GITHUB_OUTPUT
          echo "${{vars.FORCED_DEPLOYMENT_TO_PROD_AND_SC}} ${{vars.PAUSE_DAY_OF_THE_WEEK}}"

  deploy_test:
    runs-on: ubuntu-latest
    needs: [weekend_deployment_check]
    if: |
      ${{ ( vars.FORCED_DEPLOYMENT_TO_PROD_AND_SC == true ) ||
      ( needs.weekend_deployment_check.outputs.day < vars.PAUSE_DAY_OF_THE_WEEK ) }}
    steps:
      - run: echo "deployed"
