name: Automate_Deploy_Test

on:
  workflow_dispatch:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutRepo
        uses: actions/checkout@v3
      - name: add variable to env
        run: |
          export name=rajkumar
          echo ${name}
          env
      - name: access variable from env
        run: |
          echo ${name}
          env

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - name: access variable from env
        run: echo $name
