name: Automate_Deploy_Test

on:
  workflow_dispatch:

jobs:
  weekend_deployment_check:
    runs-on: ubuntu-latest
    steps:
      - name: checkoutRepo
        uses: actions/checkout@v3
      - name: Check deployment
        run: ./.github/workflows/scripts/check_deployment.sh ${{vars.FORCED_DEPLOYMENT_TO_PROD_AND_SC}} ${{vars.PAUSE_DAY_OF_THE_WEEK}}

  deploy_test:
    runs-on: ubuntu-latest
    needs: [weekend_deployment_check]
    steps:
      - run: |
          echo "deployed"
          echo "day:${{needs.weekend_deployment_check.outputs.day}} time:${{needs.weekend_deployment_check.outputs.time}}"
            - uses: actions/checkout@v1
      - id: set_state_in_progress
        name: Set deployment status to [in_progress]
        uses: rsotnychenko/deployment-status-update@0.2.1
        with:
          run_id: ${{ github.run_id }}
          status: pending
