name: Automate_Deploy_Test

on:
  push:
  workflow_dispatch:

jobs:
  first-job:
    env:
      name: raj
    runs-on: ubuntu-latest
    steps:
      - name: checkoutRepo
        uses: actions/checkout@v3
      - name: add variable to env
        run: |
          echo ${{env.name}}
          echo name=rajkumar  >> ${{env.name}}
          echo $name
      - name: access variable from env
        run: |
          echo $name

  second-job:
    runs-on: ubuntu-latest
    needs: [first-job]
    steps:
      - name: access variable from env
        run: echo $name
