name: Automate_Deploy_Test

on:
  workflow_dispatch:

jobs:
  weekend_deployment_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployment
        run: ./.github/workflows/scripts/check_deployment.sh ${{vars.FORCED_DEPLOYMENT_TO_PROD_AND_SC}} ${{vars.PAUSE_DAY_OF_THE_WEEK}}

  deploy_test:
    runs-on: ubuntu-latest
    needs: [weekend_deployment_check]
    steps:
      - run: echo "deployed"
      - run: echo "day:${{needs.weekend_deployment_check.outputs.day}} time:${{needs.weekend_deployment_check.outputs.time}}"
