name: Automate_Deploy_Test

on:
  push:
  workflow_dispatch:

jobs:
  checkoutRepo:
    uses: actions/checkout@v3

  first-job:
    outputs:
      tests: ${{ steps.step1.outputs.tests }}
    env:
      name: raj
      age: 20
    runs-on: ubuntu-latest
    steps:
      - name: add variable to env
        id: step1
        run: |
          echo "tests=16" >> $GITHUB_OUTPUT
          echo ${{env.name}}
          echo "name=rajkumar" >> $GITHUB_ENV
          echo ${{env.name}} ${{env.tests}}
      - name: access variable from env
        run: |
          echo $name
          echo $age
          echo $tests

  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: access variable from env
        run: echo ${{needs.first-job.outputs.tests}}
